[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "full-inference"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["."]
include = ["ovd*", "mllm*", "config*", "answers*", "prompting_method*"]
namespaces = true